app:
  name: robot-ingest
  environment: dev
  timezone: "Asia/Shanghai"

mqtt:
  brokerUrl: "tcp://192.168.123.61:1883"
  clientIdPrefix: "ingest-"
  cleanSession: true
  connectionTimeoutSec: 10
  keepAliveSec: 30
  qos:
    state: 0
    connection: 1
    networkIp: 1
    error: 1
    cargo: 0
  topics:
    state: "robots/+/state"
    connection: "robots/+/connection"
    networkIp: "robots/+/network/ip"
    error: "robots/+/error"
    cargo: "robots/+/cargo"
  lwt:
    enabled: true
    topicTemplate: "robots/{deviceId}/connection"
    offlinePayload: "{"connection":"offline"}"
    qos: 1
    retain: true
  reconnectBackoff:
    initialMs: 500
    maxMs: 10000
    multiplier: 2.0

redis:
  host: "192.168.123.20"
  port: 6379
  db: 0
  timeoutMs: 2000
  keys:
    latestTemplate: "robot:latest:{deviceId}"
    coreHashTemplate: "robot:corehash:{deviceId}"
    dupsTemplate: "robot:dups:{deviceId}"
  queues:
    state: "q:state"
    connection: "q:connection"
    networkIp: "q:network_ip"
    error: "q:error"
    cargo: "q:cargo"
  metricsKey: "ingest:metrics"
  stream:
    useStream: false
    consumerGroup: "writer-group"
    consumerName: "writer-1"
    maxLen: 1000000

mongodb:
  uri: "mongodb://192.168.123.46:27017"
  database: "robotdb"
  collections:
    latest: "robot_latest_state"
    stateEvents: "state_events"
    connectionEvents: "connection_events"
    networkIpEvents: "network_ip_events"
    errorEvents: "error_events"
    cargoEvents: "cargo_events"
    ingestMetrics: "ingest_metrics"
  writeConcern:
    w: 1
    j: false
    wtimeoutMs: 0

dedupe:
  enable: true
  positionQuantize:
    decimals: 6
  coreFields:
    - "battery"
    - "taskStatus"
    - "taskId"
    - "autonomousMode"
    - "fault"
    - "binsNum"
    - "coordinateType"
    - "position"
  hashAlgo: "murmur3"
  dropCounterField: "state_dropped"

batch:
  sizeTrigger: 1000
  timeTriggerSec: 60
  maxPerFlush: 5000
  backpressure:
    sleepMsOnBusy: 50

http:
  port: 8080
  managementPort: 8081
  actuator:
    enabled: true
    endpoints:
      - "health"
      - "metrics"
      - "prometheus"

# 新增：侧挂处理特性配置（默认关闭）
ingest:
  feature:
    enabled: false                      # 总开关，默认关闭
  queue:
    capacity: 10240                     # 全局队列容量
    dropWhenFull: true                  # 队满时丢弃策略
  batch:
    size: 100                          # 批量处理大小
    intervalMs: 100                    # 批量处理间隔

logging:
  level: "INFO"
  redact:
    secrets: true
